project:
  type: website
  output-dir: docs

website:
  search: false
  title: "Giorgio Paulon"
  site-url: "https://giorgiopaulon.github.io"
  navbar:
    title: false
    background: light
    pinned: true
    left:
      - text: "About"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "CV"
        href: /files/Paulon_CV.pdf
    right:
      - icon: github
        href: https://github.com/giorgiopaulon
      - icon: linkedin
        href: https://www.linkedin.com/in/giorgiopaulon
      - icon: mortarboard-fill
        href: https://scholar.google.it/citations?user=j-caV3AAAAAJ&hl=en
  page-footer:
    center:
      - text: "© 2022 Giorgio Paulon"

format:
  html:
    toc: false
    smooth-scroll: true
    anchor-sections: false
    theme: 
    - cosmo
    - styles.scss
    # theme: cosmo
    # css: styles.css
    code-overflow: wrap