---
pagetitle: "Giorgio Paulon - Research"
---


## Peer-reviewed Publications / Preprints

#### Clinical Trial Design and Implementation


* Dres, M., Ewert, R., Conrad, S. A., Ataya, A., Shrager, J., Mortaza, S., Delamaire, F., Nilius, G., Heine, A., Mehta, N., Ways, J., Evans, D., **Paulon, G.**, Khandwala, F., Berry, N., Viele, K., and others (2025). Temporary Transvenous Diaphragm Neurostimulation for Weaning from Mechanical Ventilation (RESCUE-3). *American Journal of Respiratory and Critical Care Medicine*
* Pradilla, G., Ratcliff, J. J., Hall, A. J., Saville, B. R., Allen, J. W., **Paulon, G.**, and others (2024). [Early minimally invasive removal of intracerebral hemorrhage trial.](https://www.nejm.org/doi/full/10.1056/NEJMoa2308440) *New England Journal of Medicine* **390**, 1277-1289


#### Drift-Diffusion Models for Decision Making with Applications in Neuroscience 


* Roark, C. L., **Paulon, G.**, Rebaudo, G., McHaney, J. R., Sarkar, A., Chandrasekaran, B. (2024). [Individual differences in working memory impact the trajectory of non-native speech category learning.](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0297917) *PloS one*
* Roark, C. L., **Paulon, G.**, Sarkar, A., Chandrasekaran, B. (2021). [Comparing perceptual category learning across modalities in the same individuals.](https://link.springer.com/article/10.3758/s13423-021-01878-0) *Psychonomic Bulletin & Review* **28**, 898-909
* **Paulon, G.**, Llanos, F., Chandrasekaran, B., Sarkar, A. (2021). [Bayesian semiparametric longitudinal drift-diffusion mixed models for tone learning in adults.](https://www.tandfonline.com/doi/full/10.1080/01621459.2020.1801448) *Journal of the American Statistical Association* **116**, 1114-1127 <a style="color:rgb(205,38,38);" href="https://CRAN.R-project.org/package=lddmm">[R Package]</a>
* **Paulon, G.**, Reetzke, R., Chandrasekaran, B., Sarkar, A. (2019). [Functional logistic mixed effects models for learning curves from longitudinal binary data.](https://pubs.asha.org/doi/10.1044/2018_JSLHR-S-ASTM-18-0283) *Journal of Speech, Language, and Hearing Research* **62**, 543-553 <a style="color:rgb(205,38,38);" href="https://asha.figshare.com/articles/dataset/Functional_logistic_mixed_effects_models_Paulon_et_al_2019_/7822568">[R Package]</a>


#### Other Miscellaneous Interests


* **Paulon, G.**, Müller, P., Sarkar, A. (2024). [Bayesian semiparametric hidden Markov tensor models for time varying random partitions with local variable selection.](https://projecteuclid.org/journals/bayesian-analysis/advance-publication/Bayesian-Semiparametric-Hidden-Markov-Tensor-Models-for-Time-Varying-Random/10.1214/23-BA1383.full) *Bayesian Analysis*
* **Paulon, G.**, Müller, P., Sal y Rosas, V. G. (2024). [Bayesian nonparametric bivariate survival regression for current status data.](https://projecteuclid.org/journals/bayesian-analysis/advance-publication/Bayesian-Nonparametric-Bivariate-Survival-Regression-for-Current-Status-Data/10.1214/22-BA1346.full) *Bayesian Analysis* **19**, 49-75
* **Paulon, G.**, De Iorio, M., Guglielmi, A., Ieva, F. (2020). [Joint modeling of recurrent events and survival: a Bayesian non-parametric approach.](https://academic.oup.com/biostatistics/advance-article-abstract/doi/10.1093/biostatistics/kxy026/5050476?redirectedFrom=fulltext) *Biostatistics* **21**, 1-14
* **Paulon, G.**, Trippa, L., Müller, P. (2018). [Invited comment on "Bayesian cluster analysis: point estimation and credible balls".](https://projecteuclid.org/euclid.ba/1508378464) *Bayesian Analysis* **13**, 590-593 <a style="color:rgb(205,38,38);" href="https://giorgiopaulon.github.io/Discussion_Wade">[Markdown]</a>

## Teaching

During my time as a PhD student at the University of Texas at Austin, I designed and taught the course "Statistical Learning and Inference" to a class of about 50 upper-level undergraduate students twice (Fall 2019 and Fall 2020).
The course introduced students to ideas of statistical learning and predictive modeling from a statistical, theoretical and computational perspective.
All course materials are publicly available [here](https://giorgiopaulon.github.io/SDS323/).


## Talks & Presentations


* **Invited talk**: Planning for Heterogeneous Treatment Effects: Enrichment for Treatment-Sensitive Patient Populations. *Society for Clinical Trials (SCT), Vancouver (Canada); May, 2025*
* **Invited talk**: Forecasting with Confidence: Harnessing Predictive Probabilities in Practice. *Society for Clinical Trials (SCT), Boston, MA; May, 2024*
* **Invited talk**: ENRICH: A Novel Approach to Clinical Trials in ICH. *Midwest Biopharmaceutical Statistics Workshop (MBSW), Indianapolis, IN; June, 2024*
* **Session chair**: Real World Experience in Conducting Adaptive Platform Trials. Speakers: Ed Mills (Cytel), Michelle Detry (Berry Consultants, LLC), Anna McGlothlin (Berry Consultants, LLC), Hong Yu (Massachusetts General Hospital). *Society for Clinical Trials (SCT), San Diego, CA; May, 2022*
* **Dissertation Defense**: [Bayesian partition models for local inference in longitudinal and survival data. The University of Texas at Austin](/files/slides/dissertation_defense.pdf); *August, 2021*
* **Invited talk**: Bayesian semiparametric longitudinal drift-diffusion mixed models for tone learning. *Joint Statistical Meetings (JSM), Seattle, WA; August, 2021*
* **Invited talk**: Bayesian semiparametric longitudinal drift-diffusion mixed models for tone learning. *International Society for Bayesian Analysis (ISBA), Kunming (China); July, 2021*
* **Invited talk**: Dependent mixtures: Modeling cell lineage. *International Chinese Statistical Association (ICSA), Houston, TX; December, 2020*
* **SDS Seminar Series**: Bayesian semiparametric longitudinal drift-diffusion mixed models for tone learning. The University of Texas at Austin; *February, 2020*
* **Poster**: Bayesian autoregressive models for waiting times of recurrent events. *Bayesian Young Statisticians Meeting (BAYSM), Florence (Italy); June, 2016*

